/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2010 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "nfo.h"
#include <QThreadStorage>

class NfoPrivate
{
public:
    NfoPrivate()
        : nfo_namespace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#", QUrl::StrictMode ) ),
          nrlOntologyGraph( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#", QUrl::StrictMode ) ),
          nfo_Application( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Application", QUrl::StrictMode ) ),
          nfo_Archive( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Archive", QUrl::StrictMode ) ),
          nfo_ArchiveItem( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem", QUrl::StrictMode ) ),
          nfo_Attachment( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment", QUrl::StrictMode ) ),
          nfo_Audio( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Audio", QUrl::StrictMode ) ),
          nfo_Bookmark( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Bookmark", QUrl::StrictMode ) ),
          nfo_BookmarkFolder( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#BookmarkFolder", QUrl::StrictMode ) ),
          nfo_CompressionType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType", QUrl::StrictMode ) ),
          nfo_Cursor( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Cursor", QUrl::StrictMode ) ),
          nfo_DataContainer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer", QUrl::StrictMode ) ),
          nfo_DeletedResource( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DeletedResource", QUrl::StrictMode ) ),
          nfo_Document( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Document", QUrl::StrictMode ) ),
          nfo_EmbeddedFileDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#EmbeddedFileDataObject", QUrl::StrictMode ) ),
          nfo_EncryptionStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#EncryptionStatus", QUrl::StrictMode ) ),
          nfo_Executable( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Executable", QUrl::StrictMode ) ),
          nfo_FileDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject", QUrl::StrictMode ) ),
          nfo_FileHash( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileHash", QUrl::StrictMode ) ),
          nfo_Filesystem( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem", QUrl::StrictMode ) ),
          nfo_FilesystemImage( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage", QUrl::StrictMode ) ),
          nfo_Folder( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder", QUrl::StrictMode ) ),
          nfo_Font( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Font", QUrl::StrictMode ) ),
          nfo_HardDiskPartition( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HardDiskPartition", QUrl::StrictMode ) ),
          nfo_HtmlDocument( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HtmlDocument", QUrl::StrictMode ) ),
          nfo_Icon( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Icon", QUrl::StrictMode ) ),
          nfo_Image( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Image", QUrl::StrictMode ) ),
          nfo_LocalFileDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#LocalFileDataObject", QUrl::StrictMode ) ),
          nfo_Media( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Media", QUrl::StrictMode ) ),
          nfo_MediaFileListEntry( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaFileListEntry", QUrl::StrictMode ) ),
          nfo_MediaList( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList", QUrl::StrictMode ) ),
          nfo_MediaStream( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaStream", QUrl::StrictMode ) ),
          nfo_MindMap( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MindMap", QUrl::StrictMode ) ),
          nfo_OperatingSystem( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#OperatingSystem", QUrl::StrictMode ) ),
          nfo_PaginatedTextDocument( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PaginatedTextDocument", QUrl::StrictMode ) ),
          nfo_PlainTextDocument( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument", QUrl::StrictMode ) ),
          nfo_Presentation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Presentation", QUrl::StrictMode ) ),
          nfo_RasterImage( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RasterImage", QUrl::StrictMode ) ),
          nfo_RemoteDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject", QUrl::StrictMode ) ),
          nfo_RemotePortAddress( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemotePortAddress", QUrl::StrictMode ) ),
          nfo_Software( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Software", QUrl::StrictMode ) ),
          nfo_SoftwareItem( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#SoftwareItem", QUrl::StrictMode ) ),
          nfo_SoftwareService( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#SoftwareService", QUrl::StrictMode ) ),
          nfo_SourceCode( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#SourceCode", QUrl::StrictMode ) ),
          nfo_Spreadsheet( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet", QUrl::StrictMode ) ),
          nfo_TextDocument( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#TextDocument", QUrl::StrictMode ) ),
          nfo_Trash( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Trash", QUrl::StrictMode ) ),
          nfo_VectorImage( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage", QUrl::StrictMode ) ),
          nfo_Video( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video", QUrl::StrictMode ) ),
          nfo_Visual( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Visual", QUrl::StrictMode ) ),
          nfo_WebDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#WebDataObject", QUrl::StrictMode ) ),
          nfo_Website( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Website", QUrl::StrictMode ) ),
          nfo_aspectRatio( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#aspectRatio", QUrl::StrictMode ) ),
          nfo_averageBitrate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#averageBitrate", QUrl::StrictMode ) ),
          nfo_belongsToContainer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#belongsToContainer", QUrl::StrictMode ) ),
          nfo_bitDepth( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#bitDepth", QUrl::StrictMode ) ),
          nfo_bitrateType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#bitrateType", QUrl::StrictMode ) ),
          nfo_bitsPerSample( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#bitsPerSample", QUrl::StrictMode ) ),
          nfo_bookmarks( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#bookmarks", QUrl::StrictMode ) ),
          nfo_channels( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#channels", QUrl::StrictMode ) ),
          nfo_characterCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#characterCount", QUrl::StrictMode ) ),
          nfo_characterPosition( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#characterPosition", QUrl::StrictMode ) ),
          nfo_codec( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#codec", QUrl::StrictMode ) ),
          nfo_colorCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#colorCount", QUrl::StrictMode ) ),
          nfo_colorDepth( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#colorDepth", QUrl::StrictMode ) ),
          nfo_commentCharacterCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#commentCharacterCount", QUrl::StrictMode ) ),
          nfo_compressionType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#compressionType", QUrl::StrictMode ) ),
          nfo_conflicts( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#conflicts", QUrl::StrictMode ) ),
          nfo_containsBookmark( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#containsBookmark", QUrl::StrictMode ) ),
          nfo_containsBookmarkFolder( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#containsBookmarkFolder", QUrl::StrictMode ) ),
          nfo_count( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#count", QUrl::StrictMode ) ),
          nfo_decryptedStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#decryptedStatus", QUrl::StrictMode ) ),
          nfo_definesClass( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#definesClass", QUrl::StrictMode ) ),
          nfo_definesFunction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#definesFunction", QUrl::StrictMode ) ),
          nfo_definesGlobalVariable( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#definesGlobalVariable", QUrl::StrictMode ) ),
          nfo_deletionDate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate", QUrl::StrictMode ) ),
          nfo_depiction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#depiction", QUrl::StrictMode ) ),
          nfo_depicts( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#depicts", QUrl::StrictMode ) ),
          nfo_duration( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#duration", QUrl::StrictMode ) ),
          nfo_encoding( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#encoding", QUrl::StrictMode ) ),
          nfo_encryptedStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#encryptedStatus", QUrl::StrictMode ) ),
          nfo_encryptionStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#encryptionStatus", QUrl::StrictMode ) ),
          nfo_fileCreated( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileCreated", QUrl::StrictMode ) ),
          nfo_fileLastAccessed( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileLastAccessed", QUrl::StrictMode ) ),
          nfo_fileLastModified( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileLastModified", QUrl::StrictMode ) ),
          nfo_fileName( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName", QUrl::StrictMode ) ),
          nfo_fileOwner( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileOwner", QUrl::StrictMode ) ),
          nfo_fileSize( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize", QUrl::StrictMode ) ),
          nfo_fileUrl( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileUrl", QUrl::StrictMode ) ),
          nfo_filesystemType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#filesystemType", QUrl::StrictMode ) ),
          nfo_fontFamily( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fontFamily", QUrl::StrictMode ) ),
          nfo_foundry( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#foundry", QUrl::StrictMode ) ),
          nfo_frameCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount", QUrl::StrictMode ) ),
          nfo_frameRate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate", QUrl::StrictMode ) ),
          nfo_freeSpace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#freeSpace", QUrl::StrictMode ) ),
          nfo_frontChannels( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frontChannels", QUrl::StrictMode ) ),
          nfo_hasHash( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasHash", QUrl::StrictMode ) ),
          nfo_hasMediaFileListEntry( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry", QUrl::StrictMode ) ),
          nfo_hasMediaStream( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaStream", QUrl::StrictMode ) ),
          nfo_hashAlgorithm( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm", QUrl::StrictMode ) ),
          nfo_hashValue( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue", QUrl::StrictMode ) ),
          nfo_height( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#height", QUrl::StrictMode ) ),
          nfo_horizontalResolution( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#horizontalResolution", QUrl::StrictMode ) ),
          nfo_interlaceMode( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#interlaceMode", QUrl::StrictMode ) ),
          nfo_isPasswordProtected( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected", QUrl::StrictMode ) ),
          nfo_lfeChannels( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#lfeChannels", QUrl::StrictMode ) ),
          nfo_lineCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#lineCount", QUrl::StrictMode ) ),
          nfo_losslessCompressionType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#losslessCompressionType", QUrl::StrictMode ) ),
          nfo_lossyCompressionType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#lossyCompressionType", QUrl::StrictMode ) ),
          nfo_occupiedSpace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#occupiedSpace", QUrl::StrictMode ) ),
          nfo_originalLocation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation", QUrl::StrictMode ) ),
          nfo_pageCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#pageCount", QUrl::StrictMode ) ),
          nfo_pageNumber( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#pageNumber", QUrl::StrictMode ) ),
          nfo_paletteSize( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#paletteSize", QUrl::StrictMode ) ),
          nfo_permissions( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#permissions", QUrl::StrictMode ) ),
          nfo_programmingLanguage( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#programmingLanguage", QUrl::StrictMode ) ),
          nfo_rate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#rate", QUrl::StrictMode ) ),
          nfo_rearChannels( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#rearChannels", QUrl::StrictMode ) ),
          nfo_sampleCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#sampleCount", QUrl::StrictMode ) ),
          nfo_sampleRate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#sampleRate", QUrl::StrictMode ) ),
          nfo_sideChannels( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#sideChannels", QUrl::StrictMode ) ),
          nfo_streamPosition( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#streamPosition", QUrl::StrictMode ) ),
          nfo_supercedes( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#supercedes", QUrl::StrictMode ) ),
          nfo_totalSpace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#totalSpace", QUrl::StrictMode ) ),
          nfo_uncompressedSize( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#uncompressedSize", QUrl::StrictMode ) ),
          nfo_uuid( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#uuid", QUrl::StrictMode ) ),
          nfo_verticalResolution( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#verticalResolution", QUrl::StrictMode ) ),
          nfo_width( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#width", QUrl::StrictMode ) ),
          nfo_wordCount( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#wordCount", QUrl::StrictMode ) ) {
    }

    QUrl nfo_namespace;
    QUrl nrlOntologyGraph;
    QUrl nfo_Application;
    QUrl nfo_Archive;
    QUrl nfo_ArchiveItem;
    QUrl nfo_Attachment;
    QUrl nfo_Audio;
    QUrl nfo_Bookmark;
    QUrl nfo_BookmarkFolder;
    QUrl nfo_CompressionType;
    QUrl nfo_Cursor;
    QUrl nfo_DataContainer;
    QUrl nfo_DeletedResource;
    QUrl nfo_Document;
    QUrl nfo_EmbeddedFileDataObject;
    QUrl nfo_EncryptionStatus;
    QUrl nfo_Executable;
    QUrl nfo_FileDataObject;
    QUrl nfo_FileHash;
    QUrl nfo_Filesystem;
    QUrl nfo_FilesystemImage;
    QUrl nfo_Folder;
    QUrl nfo_Font;
    QUrl nfo_HardDiskPartition;
    QUrl nfo_HtmlDocument;
    QUrl nfo_Icon;
    QUrl nfo_Image;
    QUrl nfo_LocalFileDataObject;
    QUrl nfo_Media;
    QUrl nfo_MediaFileListEntry;
    QUrl nfo_MediaList;
    QUrl nfo_MediaStream;
    QUrl nfo_MindMap;
    QUrl nfo_OperatingSystem;
    QUrl nfo_PaginatedTextDocument;
    QUrl nfo_PlainTextDocument;
    QUrl nfo_Presentation;
    QUrl nfo_RasterImage;
    QUrl nfo_RemoteDataObject;
    QUrl nfo_RemotePortAddress;
    QUrl nfo_Software;
    QUrl nfo_SoftwareItem;
    QUrl nfo_SoftwareService;
    QUrl nfo_SourceCode;
    QUrl nfo_Spreadsheet;
    QUrl nfo_TextDocument;
    QUrl nfo_Trash;
    QUrl nfo_VectorImage;
    QUrl nfo_Video;
    QUrl nfo_Visual;
    QUrl nfo_WebDataObject;
    QUrl nfo_Website;
    QUrl nfo_aspectRatio;
    QUrl nfo_averageBitrate;
    QUrl nfo_belongsToContainer;
    QUrl nfo_bitDepth;
    QUrl nfo_bitrateType;
    QUrl nfo_bitsPerSample;
    QUrl nfo_bookmarks;
    QUrl nfo_channels;
    QUrl nfo_characterCount;
    QUrl nfo_characterPosition;
    QUrl nfo_codec;
    QUrl nfo_colorCount;
    QUrl nfo_colorDepth;
    QUrl nfo_commentCharacterCount;
    QUrl nfo_compressionType;
    QUrl nfo_conflicts;
    QUrl nfo_containsBookmark;
    QUrl nfo_containsBookmarkFolder;
    QUrl nfo_count;
    QUrl nfo_decryptedStatus;
    QUrl nfo_definesClass;
    QUrl nfo_definesFunction;
    QUrl nfo_definesGlobalVariable;
    QUrl nfo_deletionDate;
    QUrl nfo_depiction;
    QUrl nfo_depicts;
    QUrl nfo_duration;
    QUrl nfo_encoding;
    QUrl nfo_encryptedStatus;
    QUrl nfo_encryptionStatus;
    QUrl nfo_fileCreated;
    QUrl nfo_fileLastAccessed;
    QUrl nfo_fileLastModified;
    QUrl nfo_fileName;
    QUrl nfo_fileOwner;
    QUrl nfo_fileSize;
    QUrl nfo_fileUrl;
    QUrl nfo_filesystemType;
    QUrl nfo_fontFamily;
    QUrl nfo_foundry;
    QUrl nfo_frameCount;
    QUrl nfo_frameRate;
    QUrl nfo_freeSpace;
    QUrl nfo_frontChannels;
    QUrl nfo_hasHash;
    QUrl nfo_hasMediaFileListEntry;
    QUrl nfo_hasMediaStream;
    QUrl nfo_hashAlgorithm;
    QUrl nfo_hashValue;
    QUrl nfo_height;
    QUrl nfo_horizontalResolution;
    QUrl nfo_interlaceMode;
    QUrl nfo_isPasswordProtected;
    QUrl nfo_lfeChannels;
    QUrl nfo_lineCount;
    QUrl nfo_losslessCompressionType;
    QUrl nfo_lossyCompressionType;
    QUrl nfo_occupiedSpace;
    QUrl nfo_originalLocation;
    QUrl nfo_pageCount;
    QUrl nfo_pageNumber;
    QUrl nfo_paletteSize;
    QUrl nfo_permissions;
    QUrl nfo_programmingLanguage;
    QUrl nfo_rate;
    QUrl nfo_rearChannels;
    QUrl nfo_sampleCount;
    QUrl nfo_sampleRate;
    QUrl nfo_sideChannels;
    QUrl nfo_streamPosition;
    QUrl nfo_supercedes;
    QUrl nfo_totalSpace;
    QUrl nfo_uncompressedSize;
    QUrl nfo_uuid;
    QUrl nfo_verticalResolution;
    QUrl nfo_width;
    QUrl nfo_wordCount;
};

QThreadStorage<NfoPrivate *> qts_nfo;
NfoPrivate* s_nfo()
{
    if (!qts_nfo.hasLocalData())
        qts_nfo.setLocalData(new NfoPrivate);
    return qts_nfo.localData();
}

QUrl Vocabulary::NFO::nfoNamespace()
{
    return s_nfo()->nfo_namespace;
}

QUrl Vocabulary::NFO::nrlOntologyGraph()
{
    return s_nfo()->nrlOntologyGraph;
}

QUrl Vocabulary::NFO::Application()
{
    return s_nfo()->nfo_Application;
}

QUrl Vocabulary::NFO::Archive()
{
    return s_nfo()->nfo_Archive;
}

QUrl Vocabulary::NFO::ArchiveItem()
{
    return s_nfo()->nfo_ArchiveItem;
}

QUrl Vocabulary::NFO::Attachment()
{
    return s_nfo()->nfo_Attachment;
}

QUrl Vocabulary::NFO::Audio()
{
    return s_nfo()->nfo_Audio;
}

QUrl Vocabulary::NFO::Bookmark()
{
    return s_nfo()->nfo_Bookmark;
}

QUrl Vocabulary::NFO::BookmarkFolder()
{
    return s_nfo()->nfo_BookmarkFolder;
}

QUrl Vocabulary::NFO::CompressionType()
{
    return s_nfo()->nfo_CompressionType;
}

QUrl Vocabulary::NFO::Cursor()
{
    return s_nfo()->nfo_Cursor;
}

QUrl Vocabulary::NFO::DataContainer()
{
    return s_nfo()->nfo_DataContainer;
}

QUrl Vocabulary::NFO::DeletedResource()
{
    return s_nfo()->nfo_DeletedResource;
}

QUrl Vocabulary::NFO::Document()
{
    return s_nfo()->nfo_Document;
}

QUrl Vocabulary::NFO::EmbeddedFileDataObject()
{
    return s_nfo()->nfo_EmbeddedFileDataObject;
}

QUrl Vocabulary::NFO::EncryptionStatus()
{
    return s_nfo()->nfo_EncryptionStatus;
}

QUrl Vocabulary::NFO::Executable()
{
    return s_nfo()->nfo_Executable;
}

QUrl Vocabulary::NFO::FileDataObject()
{
    return s_nfo()->nfo_FileDataObject;
}

QUrl Vocabulary::NFO::FileHash()
{
    return s_nfo()->nfo_FileHash;
}

QUrl Vocabulary::NFO::Filesystem()
{
    return s_nfo()->nfo_Filesystem;
}

QUrl Vocabulary::NFO::FilesystemImage()
{
    return s_nfo()->nfo_FilesystemImage;
}

QUrl Vocabulary::NFO::Folder()
{
    return s_nfo()->nfo_Folder;
}

QUrl Vocabulary::NFO::Font()
{
    return s_nfo()->nfo_Font;
}

QUrl Vocabulary::NFO::HardDiskPartition()
{
    return s_nfo()->nfo_HardDiskPartition;
}

QUrl Vocabulary::NFO::HtmlDocument()
{
    return s_nfo()->nfo_HtmlDocument;
}

QUrl Vocabulary::NFO::Icon()
{
    return s_nfo()->nfo_Icon;
}

QUrl Vocabulary::NFO::Image()
{
    return s_nfo()->nfo_Image;
}

QUrl Vocabulary::NFO::LocalFileDataObject()
{
    return s_nfo()->nfo_LocalFileDataObject;
}

QUrl Vocabulary::NFO::Media()
{
    return s_nfo()->nfo_Media;
}

QUrl Vocabulary::NFO::MediaFileListEntry()
{
    return s_nfo()->nfo_MediaFileListEntry;
}

QUrl Vocabulary::NFO::MediaList()
{
    return s_nfo()->nfo_MediaList;
}

QUrl Vocabulary::NFO::MediaStream()
{
    return s_nfo()->nfo_MediaStream;
}

QUrl Vocabulary::NFO::MindMap()
{
    return s_nfo()->nfo_MindMap;
}

QUrl Vocabulary::NFO::OperatingSystem()
{
    return s_nfo()->nfo_OperatingSystem;
}

QUrl Vocabulary::NFO::PaginatedTextDocument()
{
    return s_nfo()->nfo_PaginatedTextDocument;
}

QUrl Vocabulary::NFO::PlainTextDocument()
{
    return s_nfo()->nfo_PlainTextDocument;
}

QUrl Vocabulary::NFO::Presentation()
{
    return s_nfo()->nfo_Presentation;
}

QUrl Vocabulary::NFO::RasterImage()
{
    return s_nfo()->nfo_RasterImage;
}

QUrl Vocabulary::NFO::RemoteDataObject()
{
    return s_nfo()->nfo_RemoteDataObject;
}

QUrl Vocabulary::NFO::RemotePortAddress()
{
    return s_nfo()->nfo_RemotePortAddress;
}

QUrl Vocabulary::NFO::Software()
{
    return s_nfo()->nfo_Software;
}

QUrl Vocabulary::NFO::SoftwareItem()
{
    return s_nfo()->nfo_SoftwareItem;
}

QUrl Vocabulary::NFO::SoftwareService()
{
    return s_nfo()->nfo_SoftwareService;
}

QUrl Vocabulary::NFO::SourceCode()
{
    return s_nfo()->nfo_SourceCode;
}

QUrl Vocabulary::NFO::Spreadsheet()
{
    return s_nfo()->nfo_Spreadsheet;
}

QUrl Vocabulary::NFO::TextDocument()
{
    return s_nfo()->nfo_TextDocument;
}

QUrl Vocabulary::NFO::Trash()
{
    return s_nfo()->nfo_Trash;
}

QUrl Vocabulary::NFO::VectorImage()
{
    return s_nfo()->nfo_VectorImage;
}

QUrl Vocabulary::NFO::Video()
{
    return s_nfo()->nfo_Video;
}

QUrl Vocabulary::NFO::Visual()
{
    return s_nfo()->nfo_Visual;
}

QUrl Vocabulary::NFO::WebDataObject()
{
    return s_nfo()->nfo_WebDataObject;
}

QUrl Vocabulary::NFO::Website()
{
    return s_nfo()->nfo_Website;
}

QUrl Vocabulary::NFO::aspectRatio()
{
    return s_nfo()->nfo_aspectRatio;
}

QUrl Vocabulary::NFO::averageBitrate()
{
    return s_nfo()->nfo_averageBitrate;
}

QUrl Vocabulary::NFO::belongsToContainer()
{
    return s_nfo()->nfo_belongsToContainer;
}

QUrl Vocabulary::NFO::bitDepth()
{
    return s_nfo()->nfo_bitDepth;
}

QUrl Vocabulary::NFO::bitrateType()
{
    return s_nfo()->nfo_bitrateType;
}

QUrl Vocabulary::NFO::bitsPerSample()
{
    return s_nfo()->nfo_bitsPerSample;
}

QUrl Vocabulary::NFO::bookmarks()
{
    return s_nfo()->nfo_bookmarks;
}

QUrl Vocabulary::NFO::channels()
{
    return s_nfo()->nfo_channels;
}

QUrl Vocabulary::NFO::characterCount()
{
    return s_nfo()->nfo_characterCount;
}

QUrl Vocabulary::NFO::characterPosition()
{
    return s_nfo()->nfo_characterPosition;
}

QUrl Vocabulary::NFO::codec()
{
    return s_nfo()->nfo_codec;
}

QUrl Vocabulary::NFO::colorCount()
{
    return s_nfo()->nfo_colorCount;
}

QUrl Vocabulary::NFO::colorDepth()
{
    return s_nfo()->nfo_colorDepth;
}

QUrl Vocabulary::NFO::commentCharacterCount()
{
    return s_nfo()->nfo_commentCharacterCount;
}

QUrl Vocabulary::NFO::compressionType()
{
    return s_nfo()->nfo_compressionType;
}

QUrl Vocabulary::NFO::conflicts()
{
    return s_nfo()->nfo_conflicts;
}

QUrl Vocabulary::NFO::containsBookmark()
{
    return s_nfo()->nfo_containsBookmark;
}

QUrl Vocabulary::NFO::containsBookmarkFolder()
{
    return s_nfo()->nfo_containsBookmarkFolder;
}

QUrl Vocabulary::NFO::count()
{
    return s_nfo()->nfo_count;
}

QUrl Vocabulary::NFO::decryptedStatus()
{
    return s_nfo()->nfo_decryptedStatus;
}

QUrl Vocabulary::NFO::definesClass()
{
    return s_nfo()->nfo_definesClass;
}

QUrl Vocabulary::NFO::definesFunction()
{
    return s_nfo()->nfo_definesFunction;
}

QUrl Vocabulary::NFO::definesGlobalVariable()
{
    return s_nfo()->nfo_definesGlobalVariable;
}

QUrl Vocabulary::NFO::deletionDate()
{
    return s_nfo()->nfo_deletionDate;
}

QUrl Vocabulary::NFO::depiction()
{
    return s_nfo()->nfo_depiction;
}

QUrl Vocabulary::NFO::depicts()
{
    return s_nfo()->nfo_depicts;
}

QUrl Vocabulary::NFO::duration()
{
    return s_nfo()->nfo_duration;
}

QUrl Vocabulary::NFO::encoding()
{
    return s_nfo()->nfo_encoding;
}

QUrl Vocabulary::NFO::encryptedStatus()
{
    return s_nfo()->nfo_encryptedStatus;
}

QUrl Vocabulary::NFO::encryptionStatus()
{
    return s_nfo()->nfo_encryptionStatus;
}

QUrl Vocabulary::NFO::fileCreated()
{
    return s_nfo()->nfo_fileCreated;
}

QUrl Vocabulary::NFO::fileLastAccessed()
{
    return s_nfo()->nfo_fileLastAccessed;
}

QUrl Vocabulary::NFO::fileLastModified()
{
    return s_nfo()->nfo_fileLastModified;
}

QUrl Vocabulary::NFO::fileName()
{
    return s_nfo()->nfo_fileName;
}

QUrl Vocabulary::NFO::fileOwner()
{
    return s_nfo()->nfo_fileOwner;
}

QUrl Vocabulary::NFO::fileSize()
{
    return s_nfo()->nfo_fileSize;
}

QUrl Vocabulary::NFO::fileUrl()
{
    return s_nfo()->nfo_fileUrl;
}

QUrl Vocabulary::NFO::filesystemType()
{
    return s_nfo()->nfo_filesystemType;
}

QUrl Vocabulary::NFO::fontFamily()
{
    return s_nfo()->nfo_fontFamily;
}

QUrl Vocabulary::NFO::foundry()
{
    return s_nfo()->nfo_foundry;
}

QUrl Vocabulary::NFO::frameCount()
{
    return s_nfo()->nfo_frameCount;
}

QUrl Vocabulary::NFO::frameRate()
{
    return s_nfo()->nfo_frameRate;
}

QUrl Vocabulary::NFO::freeSpace()
{
    return s_nfo()->nfo_freeSpace;
}

QUrl Vocabulary::NFO::frontChannels()
{
    return s_nfo()->nfo_frontChannels;
}

QUrl Vocabulary::NFO::hasHash()
{
    return s_nfo()->nfo_hasHash;
}

QUrl Vocabulary::NFO::hasMediaFileListEntry()
{
    return s_nfo()->nfo_hasMediaFileListEntry;
}

QUrl Vocabulary::NFO::hasMediaStream()
{
    return s_nfo()->nfo_hasMediaStream;
}

QUrl Vocabulary::NFO::hashAlgorithm()
{
    return s_nfo()->nfo_hashAlgorithm;
}

QUrl Vocabulary::NFO::hashValue()
{
    return s_nfo()->nfo_hashValue;
}

QUrl Vocabulary::NFO::height()
{
    return s_nfo()->nfo_height;
}

QUrl Vocabulary::NFO::horizontalResolution()
{
    return s_nfo()->nfo_horizontalResolution;
}

QUrl Vocabulary::NFO::interlaceMode()
{
    return s_nfo()->nfo_interlaceMode;
}

QUrl Vocabulary::NFO::isPasswordProtected()
{
    return s_nfo()->nfo_isPasswordProtected;
}

QUrl Vocabulary::NFO::lfeChannels()
{
    return s_nfo()->nfo_lfeChannels;
}

QUrl Vocabulary::NFO::lineCount()
{
    return s_nfo()->nfo_lineCount;
}

QUrl Vocabulary::NFO::losslessCompressionType()
{
    return s_nfo()->nfo_losslessCompressionType;
}

QUrl Vocabulary::NFO::lossyCompressionType()
{
    return s_nfo()->nfo_lossyCompressionType;
}

QUrl Vocabulary::NFO::occupiedSpace()
{
    return s_nfo()->nfo_occupiedSpace;
}

QUrl Vocabulary::NFO::originalLocation()
{
    return s_nfo()->nfo_originalLocation;
}

QUrl Vocabulary::NFO::pageCount()
{
    return s_nfo()->nfo_pageCount;
}

QUrl Vocabulary::NFO::pageNumber()
{
    return s_nfo()->nfo_pageNumber;
}

QUrl Vocabulary::NFO::paletteSize()
{
    return s_nfo()->nfo_paletteSize;
}

QUrl Vocabulary::NFO::permissions()
{
    return s_nfo()->nfo_permissions;
}

QUrl Vocabulary::NFO::programmingLanguage()
{
    return s_nfo()->nfo_programmingLanguage;
}

QUrl Vocabulary::NFO::rate()
{
    return s_nfo()->nfo_rate;
}

QUrl Vocabulary::NFO::rearChannels()
{
    return s_nfo()->nfo_rearChannels;
}

QUrl Vocabulary::NFO::sampleCount()
{
    return s_nfo()->nfo_sampleCount;
}

QUrl Vocabulary::NFO::sampleRate()
{
    return s_nfo()->nfo_sampleRate;
}

QUrl Vocabulary::NFO::sideChannels()
{
    return s_nfo()->nfo_sideChannels;
}

QUrl Vocabulary::NFO::streamPosition()
{
    return s_nfo()->nfo_streamPosition;
}

QUrl Vocabulary::NFO::supercedes()
{
    return s_nfo()->nfo_supercedes;
}

QUrl Vocabulary::NFO::totalSpace()
{
    return s_nfo()->nfo_totalSpace;
}

QUrl Vocabulary::NFO::uncompressedSize()
{
    return s_nfo()->nfo_uncompressedSize;
}

QUrl Vocabulary::NFO::uuid()
{
    return s_nfo()->nfo_uuid;
}

QUrl Vocabulary::NFO::verticalResolution()
{
    return s_nfo()->nfo_verticalResolution;
}

QUrl Vocabulary::NFO::width()
{
    return s_nfo()->nfo_width;
}

QUrl Vocabulary::NFO::wordCount()
{
    return s_nfo()->nfo_wordCount;
}
